name: "Build AUR package with yay"
description: "Builds and installs an AUR package using yay in Arch Linux"
inputs:
  package:
    description: "AUR package name to build"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package }}
