name: Create Custom Arch Repository

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: soloturn/build-aur-action@master
      with:
        repo-name: plex-desktop
