name: Build AUR package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'AUR package to build'
        required: true
        default: 'plex-desktop'

jobs:
  build-aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p ${{ github.workspace }}/yay-cache

      - name: Build AUR package in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/yay-cache:/home/build/.cache/yay \
            ghcr.io/punkops/aur:latest \
            "${{ github.event.inputs.package }}"

      - name: Upload built package(s)
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: yay-cache/**/*.pkg.tar.*
